from .variants.loss.nnUNetTrainerWCELoss import nnUNetTrainerWCELoss, nnUNetTrainerWCELoss_5epochs
from .variants.loss.nnUNetTrainerWMSELoss import nnUNetTrainerWMSELoss, nnUNetTrainerWMSELoss_5epochs